# Common.
baseURL: "https://detours.sbrk.org/"
title: "Détours by Sébastien Rannou"
languageCode: "en-us"
contentdir: "content"
publishdir: "public"

# Menu.
sectionPagesMenu: "navigation"
menu:
  navigation:
    - identifier: "detours"
      name: "Détours"
      title: "Détours"
      url: /
      weight: 1
    - identifier: "exhibitions"
      name: "Exhibitions"
      title: "Exhibitions"
      url: /exhibitions/
      weight: 2
    - identifier: "photobooks"
      name: "Photobooks"
      title: "Photobooks"
      url: /books/
      weight: 3
    - identifier: "about"
      name: "About"
      title: "About"
      url: /about/
      weight: 4
