# Ran.
#
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Ran"
description = "Ran."
homepage = "http://detours.mxs.sbrk.org/"
tags = []
features = []
min_version = "0.63.2"

[author]
  name = "Sébastien Rannou"
  homepage = "https://mxs.sbrk.org/"
